In [47]:
import numpy as np

np.array([1,2,3])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
arr.shape

(3,)

In [48]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.ones((4,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [12]:
np.full((4,3), 6, dtype=int)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [52]:
arr = np.random.random((3,4))

In [53]:
arr > 0.2

array([[False,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [54]:
arr

array([[0.0102702 , 0.4830461 , 0.00505598, 0.652279  ],
       [0.89440852, 0.35439251, 0.50419493, 0.51161929],
       [0.23116908, 0.25129911, 0.41826186, 0.11364793]])

In [55]:
arr[0, 0]

0.010270203118789789

In [57]:
 arr[arr > 0.2]

array([0.4830461 , 0.652279  , 0.89440852, 0.35439251, 0.50419493,
       0.51161929, 0.23116908, 0.25129911, 0.41826186])